/**
 * planToFieldRanges — maps each field selection in the original query to the
 * subgraph (Fetch node service) that resolves it.
 *
 * Strategy:
 * 1. Collect all Fetch nodes from the PlanNode tree.
 * 2. For each Fetch, parse its `operation` string with graphql-js to learn
 *    *which* fields it resolves (field names / paths).
 * 3. Parse the original query and walk its AST to find matching fields by
 *    name, using the original AST's `loc` for accurate positions.
 *
 * This dual-parse approach is necessary because the Fetch operation is a
 * router-generated sub-selection: positions in it do not correspond to the
 * original query positions. We match by field name at each level instead.
 *
 * Edge cases handled:
 * - Fetch operation strings that fail to parse are skipped silently.
 * - The original query that fails to parse returns an empty array.
 * - Alias fields: the `loc` of the alias keyword is used when present.
 * - Inline fragments: traversed recursively.
 * - Fragment spreads: the `FragmentDefinition` is looked up and traversed.
 * - Fields in multiple Fetches (e.g. `__typename`): last Fetch's color wins.
 */

import { parse, Kind } from "graphql";
import type {
  DocumentNode,
  SelectionSetNode,
  FieldNode,
  FragmentDefinitionNode,
  InlineFragmentNode,
  FragmentSpreadNode,
} from "graphql";
import type { PlanNode } from "./core/types";

export interface FieldRange {
  /** 1-based line number in the original query string. */
  line: number;
  /** 1-based column. */
  col: number;
  /** Token length (characters). */
  len: number;
  /** The subgraph service that resolves this field. */
  service: string;
}

// ---------------------------------------------------------------------------
// Collect Fetch nodes
// ---------------------------------------------------------------------------

interface FetchEntry {
  service: string;
  operation: string;
}

function collectFetches(node: PlanNode, out: FetchEntry[] = []): FetchEntry[] {
  switch (node.kind) {
    case "Fetch":
      out.push({ service: node.service, operation: node.operation });
      break;
    case "Sequence":
    case "Parallel":
      node.nodes.forEach((n) => collectFetches(n, out));
      break;
    case "Flatten":
      collectFetches(node.node, out);
      break;
    case "Subscription":
      collectFetches(node.primary, out);
      if (node.rest) collectFetches(node.rest, out);
      break;
    case "Defer":
      if (node.primary) collectFetches(node.primary, out);
      node.deferred.forEach((d) => {
        if (d.node) collectFetches(d.node, out);
      });
      break;
    case "Condition":
      if (node.ifBranch) collectFetches(node.ifBranch, out);
      if (node.elseBranch) collectFetches(node.elseBranch, out);
      break;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Extract field names from a Fetch operation AST
// ---------------------------------------------------------------------------

/**
 * Walk a SelectionSet and return all field names (or alias names) it contains,
 * recursively entering inline fragments. Fragment spreads are left as-is since
 * we just need the set of field names present in the sub-operation.
 */
function fetchFieldNames(selectionSet: SelectionSetNode): Set<string> {
  const names = new Set<string>();
  for (const sel of selectionSet.selections) {
    if (sel.kind === Kind.FIELD) {
      names.add(sel.alias?.value ?? sel.name.value);
    } else if (sel.kind === Kind.INLINE_FRAGMENT && sel.selectionSet) {
      fetchFieldNames(sel.selectionSet).forEach((n) => names.add(n));
    }
    // Fragment spreads are skipped — sub-operations generated by the router
    // rarely contain named fragments.
  }
  return names;
}

// ---------------------------------------------------------------------------
// Walk original query AST and record positions for matched fields
// ---------------------------------------------------------------------------

function walkSelectionSet(
  selectionSet: SelectionSetNode,
  matchedFieldNames: Set<string>,
  service: string,
  fragments: Record<string, FragmentDefinitionNode>,
  results: Map<string, FieldRange>,
): void {
  for (const sel of selectionSet.selections) {
    switch (sel.kind) {
      case Kind.FIELD: {
        const fieldSel = sel as FieldNode;
        // A field matches if the Fetch operation contains its underlying field
        // name OR its alias name (routers typically use the field name, not
        // the alias, in sub-operations).
        const responseName = fieldSel.alias?.value ?? fieldSel.name.value;
        const fieldName = fieldSel.name.value;
        const isMatch = matchedFieldNames.has(responseName) || matchedFieldNames.has(fieldName);
        if (isMatch && fieldSel.loc) {
          // Position points to the alias keyword when an alias exists, so the
          // highlight starts at the same visual token the user sees in the editor.
          const startToken = fieldSel.loc.startToken;
          results.set(`${service}::${startToken.line}:${startToken.column}`, {
            line: startToken.line,
            col: startToken.column,
            len: startToken.end - startToken.start,
            service,
          });
        }
        // Always recurse into sub-selections so nested fields are found.
        if (fieldSel.selectionSet) {
          // For nested fields we don't filter by matchedFieldNames — the Fetch
          // sub-operation may not reflect the full nesting depth (the router
          // injects entity keys). Instead, record every sub-field as belonging
          // to this service too when it appears in the matched Fetch.
          walkSelectionSet(fieldSel.selectionSet, matchedFieldNames, service, fragments, results);
        }
        break;
      }
      case Kind.INLINE_FRAGMENT: {
        const inlineSel = sel as InlineFragmentNode;
        if (inlineSel.selectionSet) {
          walkSelectionSet(inlineSel.selectionSet, matchedFieldNames, service, fragments, results);
        }
        break;
      }
      case Kind.FRAGMENT_SPREAD: {
        const spreadSel = sel as FragmentSpreadNode;
        const fragment = fragments[spreadSel.name.value];
        if (fragment) {
          walkSelectionSet(fragment.selectionSet, matchedFieldNames, service, fragments, results);
        }
        break;
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns a `FieldRange` for each field selection in `originalQuery` that
 * appears in at least one Fetch node of `root`.
 *
 * When a field appears in multiple Fetch nodes (e.g. `__typename`), the
 * *last* Fetch's service color wins — acceptable for the educational use case.
 *
 * Returns an empty array if the original query cannot be parsed.
 */
export function planToFieldRanges(root: PlanNode, originalQuery: string): FieldRange[] {
  // Parse the original query first — bail out if it fails.
  let originalDoc: DocumentNode;
  try {
    originalDoc = parse(originalQuery, { noLocation: false });
  } catch {
    return [];
  }

  // Build a fragment lookup map for the original query.
  const fragments: Record<string, FragmentDefinitionNode> = {};
  for (const def of originalDoc.definitions) {
    if (def.kind === Kind.FRAGMENT_DEFINITION) {
      fragments[def.name.value] = def;
    }
  }

  // Collect all Fetch nodes from the plan.
  const fetches = collectFetches(root);
  if (fetches.length === 0) return [];

  // For each Fetch: parse its operation, extract field names it resolves, then
  // walk the original query AST and record positions.
  // We use a Map keyed by "service::line:col" so later Fetches overwrite earlier
  // ones for the same position (last Fetch wins).
  const results = new Map<string, FieldRange>();

  for (const fetch of fetches) {
    let fetchDoc: DocumentNode;
    try {
      fetchDoc = parse(fetch.operation, { noLocation: false });
    } catch {
      // Malformed sub-operation — skip without crashing.
      continue;
    }

    // Collect field names from the Fetch's top-level operation.
    const matchedNames = new Set<string>();
    for (const def of fetchDoc.definitions) {
      if (def.kind === Kind.OPERATION_DEFINITION || def.kind === Kind.FRAGMENT_DEFINITION) {
        fetchFieldNames(def.selectionSet).forEach((n) => matchedNames.add(n));
      }
    }

    if (matchedNames.size === 0) continue;

    // Walk original query definitions and record positions.
    for (const def of originalDoc.definitions) {
      if (def.kind === Kind.OPERATION_DEFINITION && def.selectionSet) {
        walkSelectionSet(def.selectionSet, matchedNames, fetch.service, fragments, results);
      }
    }
  }

  return Array.from(results.values());
}

/**
 * Collect unique service names from a PlanNode tree in first-encounter order.
 * Exported so App.tsx can derive the legend without importing planToMermaid.
 */
export function collectServiceNames(root: PlanNode): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const f of collectFetches(root)) {
    if (!seen.has(f.service)) {
      seen.add(f.service);
      out.push(f.service);
    }
  }
  return out;
}
